---
- name: prepare aws cloud
  hosts: localhost
  
  tasks:
    - name: create a new ec2 key pair
      ec2_key:
        name: key-1
        region: eu-north-1
      register: ec2_key_result
     - name: Save private key
      copy: content="{{ ec2_key_result.key.private_key }}" dest=".ssh/id_rsa" mode=0600
  
  tasks:
    - name: create security group 1
        ec2_group:
          name: Allow-In-22
          description: Open port 22 in
          region: eu-north-1
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0

    - name: create security group 2
        ec2_group:
          name: Allow-In-22-8080
          description: Open ports 22 and 8080 in
          region: eu-north-1
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0  
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
  
    - name: Launch EC2 Instance 1 (Build)
        ec2:
              key_name: key-1
              region: eu-north-1
              group: Allow-In-22
              instance_type: t3.micro
              image: ami-092cce4a19b438926
              wait: yes
              count: 1
              user_data: build.start.sh
              assign_public_ip: yes
            register: output
          - name: print
            debug:
              var: output.instances[0].public_ip
          - name: update inventory
            add_host:
              name: "{{ output.instances[0].public_ip }}"
              groups: build

- name: Artifact generation
  hosts: build
  become: yes

  tasks:
  - name: Cloning the repo
    git: 
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/user/boxfuse-sample-java-war-hello
      clone: yes
      update: yes
    
  - name: Artifact generation
    command: mvn package
    args:
        chdir: /home/user/boxfuse-sample-java-war-hello/




