---
- name: prepare cloud
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: create a new ec2 key pair
      ec2_key:
        name: key-1
        region: eu-north-1
     - name: Save private key
      copy: content="{{ ec2_key_result.key.private_key }}" dest=".ssh/id_rsa" mode=0600
  
  tasks:
    - name: create security group 1
        ec2_group:
          name: Allow-In-22
          description: Open port 22 in
          region: eu-north-1
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0

tasks:
    - name: create security group 2
        ec2_group:
          name: Allow-In-22-8080
          description: Open port 22 and 8080 in
          region: eu-north-1
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0  
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0

  



        